title: Danny Pham
description: The personal website of Danny Pham!
theme: just-the-docs
color_scheme: dark

url: "https://dannyphamv.com"
repository: dannyphamv/website

permalink: pretty

heading_anchors: false

nav_external_links:
  - title: LinkedIn Profile
    url: https://www.linkedin.com/in/dannyphamv/
    opens_in_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Highlight
    color: yellow
  note:
    title: Note
    color: blue

footer_content: "Copyright &copy; 2024 Danny Pham. Distributed by an <a href=\"https://github.com/dannyphamv/website/blob/main/LICENSE\">MIT license.</a>"
