title: Danny Pham
description: The personal website of Danny Pham!
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  LinkedIn Profile: https://www.linkedin.com/in/dannyphamv/
