title: Danny Pham
description: The personal website of Danny Pham!
theme: just-the-docs
color_scheme: dark

url: "https://dannyphamv.com"
repository: dannyphamv/website

aux_links_new_tab: true
aux_links:
  LinkedIn Profile: https://www.linkedin.com/in/dannyphamv/

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Highlight
    color: yellow
  note:
    title: Note
    color: blue

footer_content: "Copyright &copy; 2024 Danny Pham. Distributed by an <a href=\"https://github.com/dannyphamv/website/blob/main/LICENSE\">MIT license.</a>"
